import streamlit as st
import utils

# --- PAGE CONFIGURATION ---
# v9.5a: Update version number
utils.initialize_page_config("The Janus Engine v9.5a | Home")

# v9.5a: Update version number and title
st.title("🏛️ The Janus Engine v9.5a: The General's Toolkit")
st.write("An AI-powered pedagogical platform utilizing a meta-prompt architecture and a holistic lens library for intuitive, multi-perspective analysis.")

# --- SIDEBAR CONFIGURATION ---
# Render global settings (API Key)
utils.render_sidebar_settings()

st.sidebar.info("Use the links above to navigate between analysis modes. Global settings are below.")

# --- MAIN PAGE CONTENT ---

st.header("Welcome to the Next Generation of Holistic Inquiry")

# v9.5a: Update version number
st.markdown("""
The Janus Engine (v9.5a) leverages advanced AI (Gemini 2.5 Pro) to help you analyze creative works—text, images, audio, or video—from multiple perspectives simultaneously. 

It utilizes a unique **"General and Soldier"** architecture:
1. **The General (Meta-Prompt):** You select a lens (e.g., "Stoicism"), a specific persona (e.g., "Seneca"), or activate the Zeitgeist Simulation mode. The AI first analyzes your input work and designs the optimal strategy (prompt) for applying that perspective to that specific work.
2. **The Soldier (Execution):** The AI executes the custom-designed prompt, generating a deep, nuanced analysis.
""")

st.header("Analysis Modes")
st.markdown("Select an analysis mode from the navigation menu to begin:")

col1, col2 = st.columns(2)

with col1:
    st.subheader("🔬 Single Lens")
    # v9.4b: Update description
    st.write("Analyze ONE work through ONE specific lens or the Zeitgeist Simulation. Ideal for focused inquiry and iterative refinement.")

    st.subheader("🎭 Dialectical Dialogue")
    # v9.4b: Update description
    st.write("Analyze ONE work through TWO lenses or two distinct Zeitgeist simulations. The results are synthesized into a dialogue (Thesis vs. Antithesis).")

with col2:
    st.subheader("🏛️ Symposium")
    # v9.4b: Update description (Note: Symposium.py was not provided but description is updated for consistency)
    st.write("Analyze ONE work through THREE or more perspectives (including Zeitgeist). The results are woven into a multi-participant discussion.")

    st.subheader("🔄 Comparative Synthesis")
    # v9.4b: Update description
    st.write("Analyze TWO different works through the SAME lens or the same Zeitgeist context. Ideal for comparison.")

# v9.5a: Update Header and description of new features
st.header("New in v9.5a: The General's Toolkit")
st.markdown("""
Version 9.5a implements a major architectural enhancement designed to significantly increase the depth and variety of analyses generated by the engine's broadest lenses.

1. **The "General's Toolkit" Architecture (Feature/Architecture):** Broad, foundational lenses (e.g., Marxism, Feminism, Stoicism) have been upgraded from single, monolithic frameworks into dynamic "toolkits" containing multiple specialized sub-primers.
2. **"Lead and Support" Protocol (AI Logic):** When analyzing through a "toolkit" lens, the General AI no longer applies a generalized approach. Instead, it executes the "Lead and Support" protocol:
    - **Diagnose:** Identify the single most potent tool (the "Lead" sub-primer) for the specific work.
    - **Support:** Identify secondary themes from the toolkit ("Support" sub-primers).
    - **Strategize:** Craft a Soldier prompt that focuses on the Lead but integrates the Support for nuance and depth.
3. **Holistic Application:** This architecture has been applied to 10 major lenses across the library, adding 40 new specialized sub-primers.

*(This builds upon the UX Overhaul/Zeitgeist Mode (v9.4b), Foundation Patch (v9.4a), Great Library (v9.3), Refinement Loop (v9.2), Primers/Video Analysis (v9.1), and the Hybrid UI/Persona Pools (v9.0)).*
""")
